version: '3.1'

services:

  mock-server:
    container_name: mock-server
    image: ghcr.io/sreenidhize/bc51mockserver:s1
    restart: always
    ports:
      - 4000:4000

  frontend:
    container_name: frontend
    image: ghcr.io/sreenidhize/51frr:1
    restart: always
    ports:
      - 443:443
    volumes:
    - type: bind
      source: /home/ubuntu/openssl
      target: /etc/ssl
    depends_on:
    - mock-server

